os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty

osx_image: xcode8.3
before_install:
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew tap vapor/tap;
            brew update;
            brew install vapor;
        else
            eval "$(curl -sL https://apt.vapor.sh)";
            sudo apt-get install vapor;
            sudo chmod -R a+rx /usr/;
        fi

script:
    - swift build
    - swift build -c release
    - swift test

after_success:
    - eval "$(curl -sL https://raw.githubusercontent.com/vapor-community/swift/master/codecov)"

notifications:
  email:
    on_success: change
    on_failure: change
